"""Web app code generator adapter."""

from __future__ import annotations

import json
from typing import Dict

from app.generation.base import CodeGenerator
from app.planner.project_spec import ProjectSpec


class WebAppGenerator(CodeGenerator):
    """Generate a lightweight React web app scaffold."""

    def generate(self, spec: ProjectSpec) -> Dict[str, str]:
        app_name = spec.title.lower().replace(" ", "-")
        package_json = {
            "name": app_name,
            "private": True,
            "scripts": {
                "dev": "vite",
                "build": "vite build",
                "test": "vitest run",
            },
        }

        features = "\n".join(f"          <li>{feature}</li>" for feature in spec.features)
        app_tsx = (
            "export default function App() {\n"
            "  return (\n"
            "    <main>\n"
            f"      <h1>{spec.title}</h1>\n"
            "      <ul>\n"
            f"{features}\n"
            "      </ul>\n"
            "    </main>\n"
            "  );\n"
            "}\n"
        )

        return {
            "package.json": json.dumps(package_json, indent=2),
            "src/App.tsx": app_tsx,
            "README.md": f"# {spec.title}\n\nGenerated by last-minute web adapter.\n",
        }
